---
# tasks file for roles/prometheus
- name: Add Prometheus configuration template
  template:
    src: prometheus.yml.j2
    dest: /tmp/prometheus.yml

- name: Create Prometheus container
  docker_container:
    name: prometheus
    image: tanyaharutyunyan/prometheus-github-actions:{{ image_tag }}
    recreate: yes
    ports:
      - "9090:9090"
    restart: yes
    volumes:
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
    restart_policy: always