name: NGINX GitHub Actions
env:
  Image_tag: ${{ github.run_number }}

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  build-push-1:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          cd node-exporter
          docker build . --file Dockerfile --tag tanyaharutyunyan/node-exporter-github-actions:${{ env.Image_tag }}

      - name: Login the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker Hub
        run: docker push tanyaharutyunyan/node-exporter-github-actions:${{ env.Image_tag }}

  build-push-2:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          cd prometheus
          docker build . --file Dockerfile --tag tanyaharutyunyan/prometheus-github-actions:${{ env.Image_tag }}

      - name: Login the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker Hub
        run: docker push tanyaharutyunyan/prometheus-github-actions:${{ env.Image_tag }}

  deploy:

    runs-on: ubuntu-latest

    needs: [ build-push-1, build-push-2 ]

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: add keyscan
        run: |
          ssh-keyscan 16.171.71.210 >> ~/.ssh/known_hosts

      - name: Ansible playbook run
        run: |
          ansible-playbook -i inventory/hosts -e image_tag=${{ env.Image_tag }} playbook.yml